In [15]:
#Program to implement the linear regression using gradient descent.
#Developed by: B Surya Prakash
#RegisterNumber: 212224230281

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
def linear_regression(X1, y, learning_rate=0.01, num_iters=1000):

    X= np.c_[np.ones(len(X1)), X1]

    theta = np.zeros(x.shape[1]).reshape(-1,1)
    
    for _ in range(num_iters):
        predictions = (x).dot(theta).reshape(-1, 1)
        errors = (predictions - y).reshape(-1,1)
        theta -= learning_rate * (1/ len(X1)) * X.T.dot(errors)
    return theta

In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

data = pd.read_csv("50_Startups.csv")

print(data.head())



   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


In [13]:
X = data.iloc[:, :-2].values.astype(float)  
y = data.iloc[:, -1].values.astype(float).reshape(-1, 1)

scaler_X = StandardScaler()
scaler_y = StandardScaler()
X1_Scaled = scaler_X.fit_transform(X)
Y1_Scaled = scaler_y.fit_transform(y)

print('Name:B Surya Prakash')
print('Register No:212224230281')
print(X1_Scaled)
print(Y1_Scaled)




Name:B Surya Prakash
Register No:212224230281
[[ 2.01641149e+00  5.60752915e-01  2.15394309e+00]
 [ 1.95586034e+00  1.08280658e+00  1.92360040e+00]
 [ 1.75436374e+00 -7.28257028e-01  1.62652767e+00]
 [ 1.55478369e+00 -9.63646307e-02  1.42221024e+00]
 [ 1.50493720e+00 -1.07991935e+00  1.28152771e+00]
 [ 1.27980001e+00 -7.76239071e-01  1.25421046e+00]
 [ 1.34006641e+00  9.32147208e-01 -6.88149930e-01]
 [ 1.24505666e+00  8.71980011e-01  9.32185978e-01]
 [ 1.03036886e+00  9.86952101e-01  8.30886909e-01]
 [ 1.09181921e+00 -4.56640246e-01  7.76107440e-01]
 [ 6.20398248e-01 -3.87599089e-01  1.49807267e-01]
 [ 5.93085418e-01 -1.06553960e+00  3.19833623e-01]
 [ 4.43259872e-01  2.15449064e-01  3.20617441e-01]
 [ 4.02077603e-01  5.10178953e-01  3.43956788e-01]
 [ 1.01718075e+00  1.26919939e+00  3.75742273e-01]
 [ 8.97913123e-01  4.58678535e-02  4.19218702e-01]
 [ 9.44411957e-02  9.11841968e-03  4.40446224e-01]
 [ 4.60720127e-01  8.55666318e-01  5.91016724e-01]
 [ 3.96724938e-01 -2.58465367e-01  6

In [14]:
model = LinearRegression()
model.fit(X1_Scaled, Y1_Scaled)

new_data = np.array([[165349.2,136897.8,471784.1]])
new_Scaled = scaler_X.transform(new_data)
prediction = model.predict(new_Scaled)
pre = scaler_y.inverse_transform(prediction)
print(f"Predicted value: {pre}")

Predicted value: [[192521.25289008]]
